---
title: "Ebola_data_nwk"
output: pdf_document
date: "2025-07-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
sir_nwk =
"functions {
    real[] two_ode(real t, real[] y, real [] parms,  real[] x_r, int[] x_i){
        real g = parms[1];
        real b = parms[2];
        real rho = parms[3];
        real dydt[1];

        dydt[1] = - g*y[1]*log(y[1]) - b*(y[1] - y[1]*y[1]) - b*rho*y[1];
        return dydt;
        }
    vector solution(vector tau, vector theta, real[] x_r, int[] x_i){
      real b = theta[1];
      real g = theta[2];
      real rho = theta[3];
      vector[1] f;
     f[1] =  1 - tau[1] - exp(-b*(rho + tau[1])/g);
      return f;
    }
}

data{
  int<lower = 0> K;
  int<lower = 0> inf_len;
  int<lower = 0> infection_count[inf_len]; 
  real t0;
  real int_time[inf_len];
}

transformed data {
  real x_r[0];
  int x_i[0];
}

parameters {
   real<lower = 0.1> b;
    real<lower = 0, upper = b> g;
  real<lower = 0, upper = 0.015> rho;
 }

 // parameters {
 //   real<lower = 0.1> b;
 //    real<lower = 0, upper = b> g;
 //  real<lower = 0, upper = 0.015> rho;
 // }
transformed parameters{
  real<lower = 1, upper = 50> R0;
  R0 = b/g;
}

model{
real parms[3];
real smax;
real ode_sol[inf_len+1];
real ic[1];
real s[inf_len, 1];


parms[1] = g;
parms[2] = b;
parms[3] = rho;

ic[1] = 1.0;

ode_sol[1] = 1.0;
s = integrate_ode_rk45(two_ode, ic, t0, int_time, parms, x_r, x_i);
ode_sol[2:(inf_len + 1)] = s[, 1];
smax = ode_sol[(inf_len+1)];

for(i in 1:(inf_len)){
  target += infection_count[i]*(log(ode_sol[i] - ode_sol[i+1]) - log(1 - smax));
}
//target += gamma_lpdf(g|1, 1) + gamma_lpdf(b|1, 1) + uniform_lpdf(rho|0, 1);
target += gamma_lpdf(g|0.02, 0.02) + gamma_lpdf(b|0.02, 0.02) + uniform_lpdf(rho|0, 1);//+ gamma_lpdf(rho|1, 1);
}

generated quantities{
   real N_est = 0;
   real K_est = 0;
  real parms[3];
  real smax = 0;
  vector[1]tau;
  vector[3] theta;
  real ode_sol[inf_len+1];
  
  real ic[1];
  real s[(inf_len), 1];
  
  vector[1] tau_init;

  
  parms[1] = g;
  parms[2] = b;
  parms[3] = rho;
  
  ic[1] = 1.0;
  
  ode_sol[1] = 1.0;
   s = integrate_ode_rk45(two_ode, ic, t0, int_time, parms, x_r, x_i);
  ode_sol[2:(inf_len+1)] = s[, 1];
  smax = ode_sol[(inf_len+1)];
  
   N_est = K/(1-smax);
   tau_init[1] = 0.5;
   
   theta[1] = b;
   theta[2] = g;
   theta[3] = rho;
   
  tau = algebra_solver(solution, tau_init, theta, x_r, x_i);
   K_est = N_est*tau[1];
}



"
```


```{r}
file.name = "EVD_Wave3.csv"
ebola = read.csv(file.name)
t = ebola[ebola[, 3] != 0, 1]
inf_table = table(floor(t))
inf_ct = as.vector(inf_table)
infection_days = as.numeric(names(inf_table))

nwk_ct =  stan_model(model_code = sir_nwk)
nwk_data = list(
  K = 3079,
  inf_len = length(inf_ct),
  infection_count = inf_ct,
  t0 = 0,
  int_time = 1:108
) ## 1068 + previous two wave inf_sum

init_values <- function() {
  list(b = 0.2, g = 0.1, r = 0.001)
}
fit = sampling(
  nwk_ct,
  data = nwk_data,
  iter = 50000,
  chain = 4,
  cores = 4,
  seed = 1234,
  control = list(adapt_delta = .9),
  init = list(init_values(), init_values(), init_values(), init_values())
)

```


